import { EMAILJS_CONFIG } from "./config.js";

const compose = document.getElementById("compose");
const openCompose = document.getElementById("open-compose");
const closeCompose = document.getElementById("close-compose");
const sendBtn = document.getElementById("send");
const saveDraftBtn = document.getElementById("save-draft");
const preview = document.getElementById("preview");
const inboxList = document.getElementById("inbox-list");
const sentListEl = document.getElementById("sent-list");
const toast = document.getElementById("toast");
const folderButtons = document.querySelectorAll(".nav button");

let state = {
  inbox: [],
  sent: [],
  drafts: [],
  aiRewriteRequired: false
};

let activeFolder = "inbox";

// --- Utility functions ---
function showToast(msg, success = true) {
  toast.style.background = success ? "#10b981" : "#ef4444";
  toast.textContent = msg;
  toast.style.display = "block";
  setTimeout(() => (toast.style.display = "none"), 3000);
}

function renderFolder(folder) {
  const listEl = folder === "inbox" ? inboxList : sentListEl;
  listEl.innerHTML = "";
  const mails = state[folder];

  if (!mails.length) {
    listEl.innerHTML = `<div style="padding:20px;color:var(--muted)">No emails in ${folder}</div>`;
    return;
  }

  mails.forEach(mail => {
    const row = document.createElement("div");
    row.className = `email-row ${mail.unread ? "unread" : ""} ${
      mail.aiFlagged ? "ai-flagged" : ""
    }`;
    row.innerHTML = `
      <div class="avatar">${
        folder === "inbox" ? (mail.from?.[0] || "?") : "KH"
      }</div>
      <div class="meta">
        <div class="subject">
          <span class="title">${
            folder === "inbox"
              ? mail.from
              : "To: " + (mail.to || "You")
          } — ${mail.subject}</span>
          <span style="color:var(--muted);font-size:12px">${
            mail.time || ""
          }</span>
        </div>
        <div class="snippet">${mail.snippet}</div>
      </div>
    `;
    row.onclick = () => openMail(mail, folder);
    listEl.appendChild(row);
  });
}

function openMail(mail, folder) {
  preview.innerHTML = `
    <h3>${mail.subject}</h3>
    <div class="meta">${
      folder === "sent" ? "To" : "From"
    }: <b>${folder === "sent" ? mail.to : mail.from}</b> · ${
    mail.time
  }</div>
    <div class="message">${mail.body}</div>
  `;
  if (folder === "inbox") mail.unread = false;
  renderFolder(folder);
}

function switchFolder(folder) {
  activeFolder = folder;
  folderButtons.forEach(btn =>
    btn.classList.toggle("active", btn.dataset.folder === folder)
  );
  inboxList.style.display = folder === "inbox" ? "block" : "none";
  sentListEl.style.display = folder === "sent" ? "block" : "none";
  renderFolder(folder);
}

function clearCompose() {
  document.getElementById("to").value = "";
  document.getElementById("subj").value = "";
  document.getElementById("body").value = "";
}

// --- Compose modal ---
openCompose.addEventListener("click", () => (compose.style.display = "block"));
closeCompose.addEventListener("click", () => {
  compose.style.display = "none";
  clearCompose();
  state.aiRewriteRequired = false;
  sendBtn.disabled = false;
});

// --- Hybrid AI-Human Detection ---
function isAIGeneratedHybrid(text) {
  if (!text) return false;
  const lower = text.toLowerCase().trim();

  // 1️⃣ Obvious AI markers
  const obviousAI = [
    "as an ai language model",
    "generated by ai",
    "as a large language model",
    "this response was generated",
    "i am unable to",
    "i do not have personal experiences",
    "i cannot provide"
  ];
  if (obviousAI.some(p => lower.includes(p))) return true;

  // 2️⃣ Generic/formal phrases
  const genericPhrases = [
    "i hope this message finds you well",
    "i am writing to inform you",
    "could you please",
    "your prompt assistance would be appreciated",
    "thank you for your attention",
    "thank you for your understanding",
    "please let me know",
    "best regards",
    "kind regards",
    "sincerely",
    "regards"
  ];
  const genericMatches = genericPhrases.filter(p => lower.includes(p)).length;

  // 3️⃣ Sentence & punctuation analysis
  const sentences = text.split(/[.!?]/).filter(s => s.trim().length > 0);
  const avgLength = sentences.length > 0 ? text.split(/\s+/).length / sentences.length : text.split(/\s+/).length;
  const punctuationCount = (text.match(/[,;:]/g) || []).length;
  const punctuationDensity = punctuationCount / (text.split(/\s+/).length || 1);

  // 4️⃣ Personal/human indicators
  const personalIndicators = (text.match(/\b(i|me|my|we|our|student|id|department|ba|l3|khushi|2510525|today|yesterday|tomorrow)\b/gi) || []).length;

  // 5️⃣ Scoring
  let score = 0;
  if (genericMatches >= 2) score += 0.5;
  if (avgLength > 15) score += 0.2;
  if (punctuationDensity > 0.05) score += 0.1;
  if (personalIndicators < 2) score += 0.3;

  return score >= 0.6;
}

// --- Send email via EmailJS ---
async function sendEmail(to, subject, message) {
  emailjs.init(EMAILJS_CONFIG.PUBLIC_KEY);
  return emailjs.send(EMAILJS_CONFIG.SERVICE_ID, EMAILJS_CONFIG.TEMPLATE_ID, {
    to_email: to,
    subject,
    message
  });
}

// --- Send button logic ---
sendBtn.addEventListener("click", async e => {
  e.preventDefault();

  const subj = document.getElementById("subj").value.trim() || "(no subject)";
  const bodyEl = document.getElementById("body");
  const body = bodyEl.value.trim();
  const toFixed = "khushiagm08@gmail.com";

  if (!subj && !body) {
    alert("Write a subject or body before sending.");
    return;
  }

  // First AI detection check
  if (!state.aiRewriteRequired && isAIGeneratedHybrid(body)) {
    // 1️⃣ Flag + Save AI Draft
    const aiMail = {
      id: Date.now(),
      from: "AI Generated Draft",
      subject: subj,
      body,
      snippet: body.slice(0, 60),
      time: new Date().toLocaleTimeString(),
      unread: true,
      aiFlagged: true
    };
    state.inbox.unshift(aiMail);
    renderFolder("inbox");

    // 2️⃣ Send AI version for review
    try {
      await sendEmail(toFixed, `[AI Detected Draft] ${subj}`, body);
      showToast(
        "⚠ AI-generated content flagged & sent for review. Please rewrite below.",
        false
      );
    } catch (err) {
      console.error("Review send failed:", err);
      showToast("Failed to send AI draft for review.", false);
    }

    // 3️⃣ Clear body + ask rewrite
    bodyEl.value = "";
    bodyEl.focus();
    sendBtn.disabled = true;
    state.aiRewriteRequired = true;

    const onBodyEdit = () => {
      sendBtn.disabled = false;
      state.aiRewriteRequired = false;
      bodyEl.removeEventListener("input", onBodyEdit);
    };
    bodyEl.addEventListener("input", onBodyEdit);
    return;
  }

  // Second send (after rewrite)
  if (state.aiRewriteRequired && isAIGeneratedHybrid(body)) {
    showToast("⚠ Still looks AI-generated. Please rewrite again.", false);
    return;
  }

  // Send normally
  try {
    await sendEmail(toFixed, subj, body);
    const newMail = {
      id: Date.now(),
      to: toFixed,
      subject: subj,
      body,
      snippet: body.slice(0, 60),
      time: new Date().toLocaleTimeString()
    };
    state.sent.unshift(newMail);
    compose.style.display = "none";
    clearCompose();
    state.aiRewriteRequired = false;
    sendBtn.disabled = false;
    showToast(`✅ Email sent to ${toFixed}`);
    switchFolder("sent");
  } catch (err) {
    console.error("Send error:", err);
    showToast("Failed to send email. Check console.", false);
  }
});

// --- Save draft ---
saveDraftBtn.addEventListener("click", e => {
  e.preventDefault();
  const subj = document.getElementById("subj").value.trim() || "(no subject)";
  const body = document.getElementById("body").value.trim() || "";
  const to = document.getElementById("to").value.trim() || "(draft)";

  if (!subj && !body) {
    alert("Write something to save as draft.");
    return;
  }

  const draft = {
    id: Date.now(),
    from: to,
    subject: subj,
    body,
    snippet: body.slice(0, 60),
    time: "Draft",
    unread: true
  };

  state.drafts.unshift(draft);
  compose.style.display = "none";
  clearCompose();
  showToast("Draft saved");
  switchFolder("drafts");
});

// --- Folder buttons ---
folderButtons.forEach(btn =>
  btn.addEventListener("click", () => switchFolder(btn.dataset.folder))
);

// --- Initial render ---
switchFolder("inbox");
renderFolder("sent");

